version: '3'

volumes:
  mysql:
    driver: local
  solr:
    driver: local
  fcrepo:
    driver: local
  redis:
    driver: local

services:
  mysql:
    image: mysql:5.7
    env_file: .env_deployment
    volumes:
      - mysql:/var/lib/mysql

  solr:
    image: solr
    # Uncomment this if you want to access SOLR's web interface
    # ports:
    #   - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/config
      - ./solr/scripts/solr-precreate-jupiter-deployment.sh:/docker-entrypoint-initdb.d/solr-precreate-jupiter-deployment.sh

  fcrepo:
    image: murny/docker-fcrepo4
    volumes:
      - fcrepo:/fcrepo4-data
    # Uncomment this if you want to access Fedora's web interface
    # ports:
    #   - "8080:8080"

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  web:
    build: 
      context: .
      dockerfile: Dockerfile.deployment
    image: ualbertalib/jupiter
    env_file: .env_deployment
    environment:
      RAILS_SERVE_STATIC_FILES: enabled
    command: bundle exec puma -C config/puma/deployment.rb -e staging
    volumes:
      - .:/app
    expose:
      - "3000"
    depends_on:
      - mysql
      - fcrepo
      - redis
      - solr
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - web
    ports:
      - "80:80"

  # No worker yet, uncomment this when we add something...preferablly sidekiq?
  # worker:
  #   build: .
  #   image: ualbertalib/jupiter
  #   command: bundle exec sidekiq
  #   environment:
  #     RAILS_ENV: development
  #     DATABASE_URL: 'mysql2://root:mysecretpassword@mysql/'
  #     FCREPO_URL: http://fcrepo:8080/fcrepo/rest
  #     SOLR_URL: http://solr:8983/solr/development
  #     SOLR_TEST_URL: http://solr:8983/solr/test
  #     REDIS_URL: 'redis://redis/1'
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #     - fcrepo
  #     - redis
  #     - solr
